/* Copyright 2020 SiFive, Inc */
/* SPDX-License-Identifier: Apache-2.0 */

#ifndef METAL__PLATFORM__SIFIVE_SPI0_H
#define METAL__PLATFORM__SIFIVE_SPI0_H


#define METAL_SIFIVE_SPI0_0_BASE_ADDRESS 0x10014000
#define METAL_SIFIVE_SPI0_0_SIZE 0x1000

#define METAL_SIFIVE_SPI0
#define METAL_SIFIVE_SPI0_SCKDIV        0x0
#define METAL_SIFIVE_SPI0_SCKMODE       0x4
#define METAL_SIFIVE_SPI0_CSID          0x10
#define METAL_SIFIVE_SPI0_CSDEF         0x14
#define METAL_SIFIVE_SPI0_CSMODE        0x18
#define METAL_SIFIVE_SPI0_DELAY0        0x28
#define METAL_SIFIVE_SPI0_DELAY1        0x2C
#define METAL_SIFIVE_SPI0_FMT           0x40
#define METAL_SIFIVE_SPI0_TXDATA        0x48
#define METAL_SIFIVE_SPI0_RXDATA        0x4C
#define METAL_SIFIVE_SPI0_TXMARK        0x50
#define METAL_SIFIVE_SPI0_RXMARK        0x54
#define METAL_SIFIVE_SPI0_FCTRL         0x60
#define METAL_SIFIVE_SPI0_FFMT          0x64
#define METAL_SIFIVE_SPI0_IE            0x70
#define METAL_SIFIVE_SPI0_IP            0x74


#endif