/* Copyright 2020 SiFive, Inc */
/* SPDX-License-Identifier: Apache-2.0 */

#ifndef METAL__PLATFORM__RISCV_CLINT0_H
#define METAL__PLATFORM__RISCV_CLINT0_H


#define METAL_RISCV_CLINT0_0_BASE_ADDRESS 0x2000000
#define METAL_RISCV_CLINT0_0_SIZE 0x10000

#define METAL_RISCV_CLINT0
#define METAL_RISCV_CLINT0_MSIP_BASE 0x0
#define METAL_RISCV_CLINT0_MTIMECMP_BASE 0x4000
#define METAL_RISCV_CLINT0_MTIME 0xBFF8


#endif