/* Copyright 2020 SiFive, Inc */
/* SPDX-License-Identifier: Apache-2.0 */

#ifndef METAL__PLATFORM__SIFIVE_HCA0_H
#define METAL__PLATFORM__SIFIVE_HCA0_H


#define METAL_SIFIVE_HCA0_0_BASE_ADDRESS 0x10018000
#define METAL_SIFIVE_HCA0_0_SIZE 0x1000

#define METAL_SIFIVE_HCA0


#endif /* METAL__PLATFORM__SIFIVE_HCA0_H */