name: LLVM RISC-V toolchain

on: workflow_dispatch  # manual dispatch only for now

env:
    ALPINE_VERSION: a3.12
    BINUTILS_MAJVER: v2
    BINUTILS_VERSION: v2.35.1
    LLVM_MAJVER: v11
    LLVM_VERSION: v11.0.0-rc3
    NEWLIB_MAJVER: v3
    NEWLIB_VERSION: v3.3.0

jobs:
    toolchain-alpine-docker:
        name: Toolchain
        runs-on: self-hosted  #, ubuntu-latest, should be changed (security issue)
        steps:

            - name: Build a docker image with LLVM project source
              run: docker build -f docker/src/clang-${LLVM_MAJVER}.dockerfile -t clang:${LLVM_VERSION} docker/src

            - name: Build a docker image with newlib source
              run: docker build -f docker/src/newlib-${NEWLIB_MAJVER}.dockerfile -t newlib:${NEWLIB_VERSION} docker/src

            - name: Build binutils for RISC-V
              run: docker build -f docker/src/binutils-riscv-${BINUTILS_MAJVER}.dockerfile -t binutils-riscv:${ALPINE_VERSION}-${BINUTILS_VERSION} docker/src

            - name: Build LLVM toolchain for RISC-V
              run: docker build -f docker/src/llvm-riscv-${LLVM_MAJVER}.dockerfile -t llvm-riscv:${ALPINE_VERSION}-${LLVM_VERSION} docker/src

            - name: Package LLVM toolchain for RISC-V
              run: docker build -f docker/src/clang-riscv-${LLVM_MAJVER}.dockerfile -t clang-riscv:${ALPINE_VERSION}-${LLVM_VERSION} docker/src

            - name: Package C newlib and compiler tuntime for RISC-V 64 bit targets
              run: docker build -f docker/src/clang-riscv64-${LLVM_MAJVER}.dockerfile -t clang-riscv64:${ALPINE_VERSION}-${LLVM_VERSION} docker/src

            - name: Package C newlib and compiler tuntime for RISC-V 32 bit targets
              run: docker build -f docker/src/clang-riscv32-${LLVM_MAJVER}.dockerfile -t clang-riscv32:${ALPINE_VERSION}-${LLVM_VERSION} docker/src

            - name: Tag Docker images
              run: docker tag binutils-riscv:${ALPINE_VERSION}-${BINUTILS_VERSION} sifive/binutils-riscv:${ALPINE_VERSION}-${BINUTILS_VERSION} &&
                   docker tag clang-riscv:${ALPINE_VERSION}-${LLVM_VERSION} sifive/clang-riscv:${ALPINE_VERSION}-${LLVM_VERSION} &&
                   docker tag clang-riscv32:${ALPINE_VERSION}-${LLVM_VERSION} sifive/clang-riscv32:${ALPINE_VERSION}-${LLVM_VERSION} &&
                   docker tag clang-riscv64:${ALPINE_VERSION}-${LLVM_VERSION} sifive/clang-riscv64:${ALPINE_VERSION}-${LLVM_VERSION}

            - name: Login to DockerHub Registry
              run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

            - name: Push the images to Docker hub
              run: docker push sifive/binutils-riscv:${ALPINE_VERSION}-${BINUTILS_VERSION} &&
                   docker push sifive/clang-riscv:${ALPINE_VERSION}-${LLVM_VERSION} &&
                   docker push sifive/clang-riscv32:${ALPINE_VERSION}-${LLVM_VERSION} &&
                   docker push sifive/clang-riscv64:${ALPINE_VERSION}-${LLVM_VERSION}

            - name: Logout from to DockerHub Registry
              run: docker logout
